# Generated by Django 2.0 on 2019-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0004_jsonfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reviewer_id', models.CharField(max_length=128)),
                ('reviewer_name', models.CharField(max_length=128)),
                ('sentiment_threshold', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
