# Generated by Django 2.0 on 2019-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0005_userthreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductreviewafterspam',
            name='review_text',
            field=models.CharField(max_length=10000),
        ),
    ]
