# Generated by Django 2.0 on 2019-05-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0006_auto_20190502_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductReviewBeforeSpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=128)),
                ('product_name', models.CharField(max_length=128)),
                ('reviewer_id', models.CharField(max_length=128)),
                ('reviewer_name', models.CharField(max_length=128)),
                ('review_text', models.CharField(max_length=10000)),
                ('overall_rating', models.DecimalField(decimal_places=4, max_digits=11, null=True)),
                ('summary_product', models.CharField(max_length=500)),
                ('timestamp_review', models.IntegerField(blank=True, default=0, null=True)),
                ('date_review', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
