# Generated by Django 2.2.6 on 2019-11-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0007_userproductreviewbeforespam'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='random_string',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
