# Generated by Django 2.2.6 on 2019-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0008_authuser_random_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='private_key',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='random_string',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
