# Generated by Django 2.2.6 on 2019-11-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0009_auto_20191121_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('center_name', models.CharField(blank=True, max_length=128, null=True)),
                ('public_key', models.CharField(blank=True, max_length=100000, null=True)),
                ('private_key', models.CharField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
