# Generated by Django 2.2.6 on 2019-11-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0010_registrationcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationCenter',
        ),
    ]
