# Generated by Django 2.2.6 on 2019-11-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0011_delete_registrationcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('center_name', models.CharField(blank=True, max_length=128, null=True)),
                ('public_key', models.CharField(blank=True, max_length=100000, null=True)),
                ('private_key', models.CharField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
