# Generated by Django 2.2.6 on 2019-11-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0012_registrationcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='random_string',
        ),
    ]
