# Generated by Django 2.2.6 on 2019-11-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0013_remove_authuser_random_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='random_string',
            field=models.CharField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
