# Generated by Django 2.2.6 on 2019-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('early_review', '0014_authuser_random_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='random_string',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
